### ISSUE TITLE
Webpack support?

### ISSUE THREAD

**Issue by crafterm** [greenish/react-mount#1]
Hi There,

Tool looks great - I'm getting an "Uncaught TypeError: React.mount is not a function" when including react-mount in a webpack bundle and attempting to use it within a script tag on a page:

The web pack bundle has

```
var mount = React.mount;
```

in the main entry file, following the Vanilla JS instructions.

Is that the correct method, or is there a better way to have react-mount imported when using web pack to manage dependencies.

In my particular case I'd like to be able to call React.mount from a script tag, generated from a Rails template that includes that webpack generated bundle if that helps clarify things?

Cheers,

Marcus

**Comment by crafterm** [comment]
Just to follow up, using the alternative AMD/Browserify import statement in the Webpack entry file

```
var mount = require("react-mount");
```

results in quite a few warnings and errors, starting with the following:

```
WARNING in ./~/react-mount/react-mount.js
Critical dependencies:
11:10-17 require function is used in a way, in which dependencies cannot be statically extracted
 @ ./~/react-mount/react-mount.js 11:10-17

WARNING in ./~/react-mount/package.json
Module parse failed: /....../node_modules/react-mount/package.json Line 2: Unexpected token :
You may need an appropriate loader to handle this file type.
| {
|   "name": "react-mount",
|   "version": "0.1.2",
|   "author": {
 @ ./~/react-mount ^\.\/.*$

```

**Comment by ph101pp** [comment]
Hi Marcus, 

I haven't used Webpack myself, therefore the lack of testing it.. 
I'll have a look at it this evening.

**Comment by crafterm** [comment]
Hi Philipp,

Thanks mate, looking forward to any insight, would be great to use it with webpack, if I can help in any way please let me know.

Cheers,

Marcus

**Comment by ph101pp** [comment]
Hi Marcus,

Check out `v0.1.3`. This version should build fine with webpack. (using `require("react-mount");`)

Let me know if it worked or if you have any other issues.

cheers,
Philipp
